/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ProvaPSC.apresentacao;

/**
 *
 * @author Biblioteca
 */
public class TelaPrincipalForm extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalForm
     */
    public TelaPrincipalForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPrincipal = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        itmCadastrarMesReferencia = new javax.swing.JMenuItem();
        itmCadastrarContaCliente = new javax.swing.JMenuItem();
        menuExibir = new javax.swing.JMenu();
        itmListaContaDeLuz = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Principal GSZ_Luz");
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(420, 320));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GSZ_LUZ - Menu Principal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastrar");

        itmCadastrarMesReferencia.setText("Mês de Referência");
        itmCadastrarMesReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarMesReferenciaActionPerformed(evt);
            }
        });
        menuCadastro.add(itmCadastrarMesReferencia);

        itmCadastrarContaCliente.setText("Conta do Cliente");
        itmCadastrarContaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarContaClienteActionPerformed(evt);
            }
        });
        menuCadastro.add(itmCadastrarContaCliente);

        menuPrincipal.add(menuCadastro);

        menuExibir.setText("Exibir");

        itmListaContaDeLuz.setText("Lista de Conta de Luz");
        itmListaContaDeLuz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListaContaDeLuzActionPerformed(evt);
            }
        });
        menuExibir.add(itmListaContaDeLuz);

        menuPrincipal.add(menuExibir);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarMesReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarMesReferenciaActionPerformed
        TelaCadastroMesForm telaCadastroMesForm = new TelaCadastroMesForm();
        telaCadastroMesForm.setVisible( true);
    }//GEN-LAST:event_itmCadastrarMesReferenciaActionPerformed

    private void itmCadastrarContaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarContaClienteActionPerformed
        TelaCadastroContaForm telaCadastroContaForm = new TelaCadastroContaForm();
        telaCadastroContaForm.setVisible( true);
    }//GEN-LAST:event_itmCadastrarContaClienteActionPerformed

    private void itmListaContaDeLuzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListaContaDeLuzActionPerformed
        TelaListaContaLuzForm telaListaContaLuzForm = new TelaListaContaLuzForm();
        telaListaContaLuzForm.setVisible( true);
    }//GEN-LAST:event_itmListaContaDeLuzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCadastrarContaCliente;
    private javax.swing.JMenuItem itmCadastrarMesReferencia;
    private javax.swing.JMenuItem itmListaContaDeLuz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenu menuExibir;
    private javax.swing.JMenuBar menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
