/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.ProvaPSC.apresentacao;

import br.edu.ifnmg.ProvaPSC.entidade.MesReferencia;
import br.edu.ifnmg.ProvaPSC.excecao.MesReferenciaBandeiraNaoSelecionadaException;
import br.edu.ifnmg.ProvaPSC.excecao.MesReferenciaCamposNaoPreenchidosException;
import br.edu.ifnmg.ProvaPSC.excecao.MesReferenciaException;
import br.edu.ifnmg.ProvaPSC.excecao.MesReferenciaTarifanegativaException;
import br.edu.ifnmg.ProvaPSC.negocio.MesReferenciaBO;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Biblioteca
 */
public class TelaCadastroMesForm extends javax.swing.JFrame {
    
    private static MesReferencia mesReferencia = new MesReferencia();
    private static MesReferenciaBO mesReferenciaBO = new MesReferenciaBO();
    /**
     * Creates new form TelaCadastroMesForm
     */
    public TelaCadastroMesForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        lblBandeira = new javax.swing.JLabel();
        cbmBandeira = new javax.swing.JComboBox<String>();
        lblTarifa = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JFormattedTextField();
        lblMes = new javax.swing.JLabel();
        txtMes = new javax.swing.JFormattedTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JFormattedTextField();
        pnlBotoes = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        lblMensagemPreencherCampos = new javax.swing.JLabel();
        lblMensagemMes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro do Mês de Referência");
        setPreferredSize(new java.awt.Dimension(420, 320));
        setSize(new java.awt.Dimension(400, 300));

        pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro do Mês de Refêrencia", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblBandeira.setText("Bandeira*: ");

        cbmBandeira.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma opção", "Verde", "Amarela", "Vermelha - Patamar 1", "Vermelha - Patamar 2" }));

        lblTarifa.setText("Tarifa*: ");

        txtTarifa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));

        lblMes.setText("Mes*: ");

        txtMes.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("MM"))));

        lblAno.setText("Ano*: ");

        txtAno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy"))));

        pnlBotoes.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnSalvar.setText("Salvar");
        btnSalvar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.setPreferredSize(new java.awt.Dimension(85, 30));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBotoesLayout = new javax.swing.GroupLayout(pnlBotoes);
        pnlBotoes.setLayout(pnlBotoesLayout);
        pnlBotoesLayout.setHorizontalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBotoesLayout.setVerticalGroup(
            pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotoesLayout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(pnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblMensagemPreencherCampos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagemPreencherCampos.setText("Preencha todos os campos assinalados com o \"*\".");

        lblMensagemMes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagemMes.setText("O campo do mês deve ser preenchido com um valor em inteiro.");

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMensagemPreencherCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAno)
                            .addComponent(lblMes)
                            .addComponent(lblTarifa)
                            .addComponent(lblBandeira))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbmBandeira, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTarifa)
                            .addComponent(txtMes, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAno, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(lblMensagemMes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAno)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMes)
                    .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTarifa)
                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBandeira)
                    .addComponent(cbmBandeira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensagemPreencherCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMensagemMes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        String mensagem = "Deseja realmente voltar ao menu principal?";
        int opcao = JOptionPane.showConfirmDialog(this, mensagem, "Mensagem de verificação", JOptionPane.YES_NO_OPTION);
        
        if( opcao == JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            this.recumperaCampos();
            mesReferenciaBO.insertMesReferecia( mesReferencia);
            JOptionPane.showMessageDialog(this, "Mês de referência cadastrado com sucesso.\n", "Mensagem de confirmação", JOptionPane.INFORMATION_MESSAGE);
            this.limparTela();
        } catch (MesReferenciaException ex) {
            JOptionPane.showMessageDialog(this, "Erro: "+ex.getMessage(), "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Erro na conversão erro: "+ex.getMessage(), "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Falha na conexão com o banco de dados erro: "+ex.getMessage(), "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Falha desconhecida procure o administrador do sistema erro: "+ex.getMessage(), "Mensagem de erro", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroMesForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroMesForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbmBandeira;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblBandeira;
    private javax.swing.JLabel lblMensagemMes;
    private javax.swing.JLabel lblMensagemPreencherCampos;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblTarifa;
    private javax.swing.JPanel pnlBotoes;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JFormattedTextField txtAno;
    private javax.swing.JFormattedTextField txtMes;
    private javax.swing.JFormattedTextField txtTarifa;
    // End of variables declaration//GEN-END:variables

    private void recumperaCampos() throws MesReferenciaException, ParseException {
      
        DecimalFormat decimalFormat = new DecimalFormat("#,###.00");
        
        String ano = txtAno.getText().trim();
        if( !ano.equals("")){
            int anoInt = Integer.parseInt(ano);
            mesReferencia.setAno( anoInt);
        }else{
            throw new MesReferenciaCamposNaoPreenchidosException();
        }
        
        String mes = txtMes.getText().trim();
        if( !mes.equals("")){
            int mesInt =  Integer.parseInt(mes);
            mesReferencia.setMes(mesInt);
        }else{
            throw new MesReferenciaCamposNaoPreenchidosException();
        }
        
        String tarifa = txtTarifa.getText().trim();
        if( !tarifa.equals("")){
            
            Number tarifaDoube = decimalFormat.parse(tarifa);
            
            Double tarifaDouble = Double.valueOf( tarifaDoube.toString()).doubleValue();
            
            if( tarifaDouble > 0){
                    mesReferencia.setTarifa(tarifaDouble);
            }else{
                throw new MesReferenciaTarifanegativaException();
            }
        }else{
            throw new MesReferenciaCamposNaoPreenchidosException();
        }
        
        int opcao = cbmBandeira.getSelectedIndex();
        if( opcao > 0){
            mesReferencia.setBandeira( opcao);
        }else{
            throw new MesReferenciaBandeiraNaoSelecionadaException();
        }
    }

    private void limparTela() {
        this.txtAno.setText("");
        this.txtMes.setText("");
        this.txtTarifa.setText("");
        this.cbmBandeira.setSelectedIndex(0);
    }
}
